@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package etaoinshrdlcumwfgypbvkjxqz.capablecables.common.registrable.materials;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;
