@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package etaoinshrdlcumwfgypbvkjxqz.$modId__.common.registrable.items.templates;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;
