@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
@FieldsAreNonnullByDefault
@LocalVariablesAreNonnullByDefault
package $group__.$modId__.annotations;

import javax.annotation.ParametersAreNonnullByDefault;
