@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
@FieldsAreNonnullByDefault
@LocalVariablesAreNonnullByDefault
package $group__.annotations;

import javax.annotation.ParametersAreNonnullByDefault;
