@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
@FieldsAreNonnullByDefault
@LocalVariablesAreNonnullByDefault
package $group__.utilities.minecraft.internationalization;

import $group__.annotations.FieldsAreNonnullByDefault;
import $group__.annotations.LocalVariablesAreNonnullByDefault;
import $group__.annotations.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;
