@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package io.github.etaoinshrdlcumwfgypbvkjxqz.utilities;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;
