@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
@FieldsAreNonnullByDefault
@LocalVariablesAreNonnullByDefault
package $group__.$modId__.annotations.runtime.processors.bases;

import javax.annotation.ParametersAreNonnullByDefault;
