@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package io.github.etaoinshrdlcumwfgypbvkjxqz.client;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;
