@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package etaoinshrdlcumwfgypbvkjxqz.capablecables.common.registrable.blocks;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;
