@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package etaoinshrdlcumwfgypbvkjxqz.$modId__.utilities.constructs;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;
