@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package etaoinshrdlcumwfgypbvkjxqz.$modId__.common.registrable.utilities;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;
